### ISSUE TITLE
Create Github Actions for sz-sdk-csharp

### ISSUE THREAD

**Issue by kernelsam** [senzing-garage/sz-sdk-csharp#35]
Create GitHub actions that do: 

- [x] **Code coverage:** [coverlet.collector](https://www.nuget.org/packages/coverlet.collector/), irongut/CodeCoverageSummary
- [x]  **Code linting checking:** [dotnet format](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-format)
- [x] **Code format checking:**[csharpier](https://csharpier.com/docs/ContinuousIntegration)
- [x] **Security checking:** [.Net Analyzers](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/overview?tabs=net-8#code-quality-analysis) codeql
- [x] **Static analysis:** [Roslyn Analyzers](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/overview?tabs=net-8)
- [x] **Unit testing:** `dotnet test`

https://learn.microsoft.com/en-us/community/content/how-to-enforce-dotnet-format-using-editorconfig-github-actions
https://github.com/dotnet/sdk/tree/main/documentation/format/docs

### References

- https://github.com/senzing-garage/garage-roadmap/issues/6

**Comment by barrycaceres** [comment]
Completed
